(lang dune 3.20)

(name exercises)

(generate_opam_files true)

(source
 (github username/reponame))

(authors "Carine Morel <carine@tarides.com>")

(maintainers "Carine Morel <carine@tarides.com>")

(license ISC)

(documentation https://url/to/documentation)

(package
 (name exercises)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends
  ocaml
  (dscheck :with-test)
  (qcheck-stm :with-test))
 (tags
  ("add topics" "to describe" your project)))
